#!/bin/bash

source $(dirname $0)/functions

header "environment info"
vsw --version
echo Running on $(tty)
echo "-"

# create user 1

USER1="user1"
PASS1="$(pwgen)"

header "vsw-setup with timeout"

RESP="$(echo $PASS1 | timeout --foreground 10 vsw setup -n $USER1 -p)"
r=$?
echo "Result  : $r"
echo "Response: $RESP"
DID1="$(echo "$RESP" | grep -e "^Created new public DID:" | cut -d " " -f 5)"
VER1="$(echo "$RESP" | grep "^Verkey: " | cut -d " " -f 2)"

[[ "${DID1:-}" != "" ]] || fail "empty DID"
[[ "${VER1:-}" != "" ]] || fail "empty verkey"

echo "DID1    : $DID1"
echo "-"

header "registering $USER1 with sovrin"

RESP="$(curl \
	--silent \
	--header "Content-Type: application/json" \
	--request POST \
	--data "{\"network\":\"buildernet\",\"did\":\"$DID1\",\"verkey\":\"$VER1\",\"paymentaddr\":\"\"}" \
	https://selfserve.sovrin.org/nym)"
r=$?

[[ $r == 0 ]] || fail "curl fails with error code $r"

STATUS="$(echo $RESP | jq .statusCode)"

[[ $STATUS == 200 ]] && echo "Registration successful." || { echo $RESP ; fail "registration failed, status $STATUS" ; }
echo "-"

header "running vsw setup again"

#RESP="$(echo $PASS1 | timeout --foreground --signal=SIGHUP --kill-after=5 50 vsw setup -n $USER1)" &
RESP="$(echo $PASS1 | vsw setup -n $USER1)" &
waitfor 60 $! || fail "re-setup timed out"

exit 1
exit $r
