#!/bin/bash

source $(dirname $0)/functions

# create connection with the repo

header "Creating connection"

vsw init -c || fail "vsw init -c failed, error $?"

# create credential definition

header "Creating credential definition"

vsw init -cd || fail "vsw init -cd failed, error $?"

