#!/bin/bash

source $(dirname $0)/functions

#test2: create and open wallet

echo "Creating new wallet: wallet1 (developer)..."
vsw setup newwallet wallet1 -k 12345
echo "Opening wallet1..."
vsw setup wallet wallet1 -k 12345
DDID=$(vsw list -w|jq '.results[].did')
DDID=$(sed -e 's/^"//' -e 's/"$//' <<<"$DDID")
echo "Developer's DID is $DDID"

# NOTE: when scripts are split like this, variables won't survive from one test
# to another without saving them for later. DDID is one such variable.

save DDID
