#!/bin/bash

source $(dirname $0)/functions

#
# create connection with the repo
#

header "Opening wallet (90 sec timeout)"

echo Pass ${pass[1]:0:10} ...

RESP="$(echo ${pass[1]} | vsw setup -n user1)" &
waitfor 90 $! || fail "opening wallet timed out after 90 seconds, error $?"

header "Processes now:"
ps auxw

header "Netstat now:"
netstat -na -p

header "Initializing connection"

RESP="$(vsw init -c)" || fail "vsw init -c failed, error $?"

#
# create credential definition
#

header "Creating credential definition"

vsw init -cd || fail "vsw init -cd failed, error $?"
