#!/bin/bash

source $(dirname $0)/functions

#
# create connection with the repo
#

header "Opening wallet (90 sec timeout)"

echo Pass ${pass[1]:0:10} ...

echo ${pass[1]} | timeout --foreground -k 2 90 vsw setup -n user1 -pn 7060,7061,7062
r=$?
[[ $r == 0 ]] || fail "opening wallet failed, error $?"

echo "- checking for localtunnel up"

r=$(ps auxw | grep -c "node /usr/bin/npx localtunnel ")
[[ $r == 0 ]] && fail "localtunnel not up"

echo "- localtunnel started"

# workaround for issue #98

sleep 5

header "Initializing connection"

RESP="$(vsw init -c)" || fail "vsw init -c failed, error $?"

echo PASS
