#!/bin/bash

source $(dirname $0)/functions

#
# list connections
#


echo ${pass[1]} | timeout --foreground -k 2 90 vsw setup -n user1 -pn 7060,7061,7062
RESP="$(vsw init -c)" || fail "vsw init -c failed, error $?"

header "Listing connections"

vsw list -c || fail "vsw list -c failed, error $?"

echo PASS

