#!/bin/bash

source $(dirname $0)/functions

#test20: test revocation 

echo "Opening wallet1 (developer)..."

#read rev_reg_id and cred_rev_id
vsw setup wallet wallet1 -k 12345
echo "Revoking -rev $REV_REG_ID  -cred $CRED_REV_ID"
vsw revoke -rev $REV_REG_ID  -cred $CRED_REV_ID
echo "Closing wallet1 ..."
vsw exit
