#!/bin/bash

source $(dirname $0)/functions

#test21: test verify fail for revoked credential
echo "Opening wallet3 (tester) ..."
vsw setup wallet wallet3 -k 12345

vsw verify -p $(dirname $0)/V1.json
echo "The above test should fail"
