#!/bin/bash

source $(dirname $0)/functions

#test22: make sure the remaining unrevoked credential is still good
vsw verify -p $(dirname $0)/V2.json
echo "The above test should pass"
vsw verify -p $(dirname $0)/V3.json
echo "The above test should pass"
vsw verify -p $(dirname $0)/V4.json
echo "The above test should pass"
vsw verify -p $(dirname $0)/V5.json
echo "The above test should fail"
vsw verify -p $(dirname $0)/V6.json
echo "The above test should fail"

echo "All tests done."
echo "Closing wallet3..."
vsw exit
